### ISSUE TITLE
Read timeout for AWS endpoints 

### ISSUE THREAD

**Issue by yozank** [hazelcast/hazelcast-aws#103]
We set connection timeouts for the initial connection to AWS endpoints ([here](https://github.com/hazelcast/hazelcast-aws/blob/740e233aa49662e4385d42da3af57c3d9c00bb35/src/main/java/com/hazelcast/aws/impl/DescribeInstances.java#L289) and [here](https://github.com/hazelcast/hazelcast-aws/blob/740e233aa49662e4385d42da3af57c3d9c00bb35/src/main/java/com/hazelcast/aws/utility/MetadataUtil.java#L69)). 

However, we don't set any read timeout so the queries may get stuck after the initial connection if any problem occurs at AWS side. 

To prevent this, we need to introduce read timeout in URLConnection's and make it configurable through the AWS config.

**Comment by hasancelik** [comment]
Small hints and starting points for first time contributors,

- As mentioned above comment, `connectionReadTimeout` value should be configurable via Hazelcast [config files or java-based](https://github.com/hazelcast/hazelcast-aws/blob/master/README.md#configuration), so you need to add new configuration parameter into [AWSConfig](https://github.com/hazelcast/hazelcast-aws/blob/master/src/main/java/com/hazelcast/aws/AwsConfig.java) class.
- Then you need to pass this value to where URL connections are initiated like existing `connectionTimeoutSeconds` config parameter.

**Comment by peterjot** [comment]
After discussion with @Holmistr, I would like to take this issue. Could you please assign it to me?

**Comment by hasancelik** [comment]
Sounds perfect @peterjot, I have assigned you to this GH issue 👍
