### ISSUE TITLE
Reduce the default number of retries to 3 and add error logging

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast-aws#107]

**Comment by alparslanavci** [comment]
@leszko, there is an existing error logging in `RetryUtils`: https://github.com/alparslanavci/hazelcast-aws/blob/master/src/main/java/com/hazelcast/aws/utility/RetryUtils.java#L59

Do you mean anywhere else?

**Comment by leszko** [comment]
The behavior should be that in case of an error, calls to AWS REST API are retries 3 times and then the error from AWS REST API is printed to the user. If you checked that's the behavior, then that's all we need :)

**Comment by alparslanavci** [comment]
Yes, it is escalating the error from AWS REST API to the user at the end of retries. I will update the default with a commit. Closing this issue now.

**Comment by alparslanavci** [comment]
See https://github.com/hazelcast/hazelcast-aws/commit/490bc3b9fdde5a77c60fa0dadf45c46d47246917 for the fix.
