### ISSUE TITLE
Print an error message in case of wrong region

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast-aws#108]
Currently, if you specify `<region>eu-central-1a</region>` (zone instead of region), then it fails without any error message. That is very hard to debug.

We should detect such situation and print a comprehensive message to the user.

**Comment by lucas-svieira** [comment]
Hello everyone!

I think I might take a stab at it as my first contribution. Is this okay?

**Comment by leszko** [comment]
Sounds perfect @lucas-svieira ! I assigned you to this GH issue. Thanks!

**Comment by leszko** [comment]
Just a few guidelines from my side :) 

1. You can add a method like `validateRegion(region)` somewhere [here](https://github.com/hazelcast/hazelcast-aws/blob/master/src/main/java/com/hazelcast/aws/AwsDiscoveryStrategy.java#L99)

2. It does not need to be super smart, but I'd rather not hardcode AWS Regions/Zones, because AWS may add new regions. You can check e.g. maybe all regions end with a "-<digit>". Then you can throw an exception.

3. Please include also a unit test :)

**Comment by lucas-svieira** [comment]
Sure thing!

Are there any contribution guidelines I should follow? Just so the PR process goes smoothly!

**Comment by leszko** [comment]
> Are there any contribution guidelines I should follow? Just so the PR process goes smoothly!

Not really, before merging you'll need to sign this: https://hazelcast.atlassian.net/wiki/spaces/COM/pages/6357071/Hazelcast+Contributor+Agreement

> Edit: and a quick question, but which JDK should I use?

Your change should be compatible with 1.8+. So you can use any JDK 8 (or later, but make sure it compiles with JDK 8).
