### ISSUE TITLE
Hazelcast In ECS Couldn't connect to the AWS service

### ISSUE THREAD

**Issue by lmnzr** [hazelcast/hazelcast-aws#116]
Okay so I tried to follow exactly written in

https://hazelcast.com/blog/how-to-set-up-hazelcast-imdg-on-aws-ecs/

Still I keep getting this error ?
com.hazelcast.aws.utility.RetryUtils : Couldn't connect to the AWS service, [1] retrying in 1 seconds...

My cluster doesn't seems able to found each other.

Can anyone give me a tips on what should I improve to make the cluster works?

**Comment by leszko** [comment]
@lmnzr If you wait some more time, do you get any stracktrace with the exception?

If not, then please change the parameter `<connection-retries>0</connection-retries>`. When set to `0`, you should see some stacktrace in the logs. That could give a hint what's wrong.

**Comment by lmnzr** [comment]
It is working now, I just downgrading the Hazelcast  to v 3.8. I don't know if there is any missing setup or whatever make it different  from the newer version.
