### ISSUE TITLE
Hide internal classes from the public

### ISSUE THREAD

**Issue by pivovarit** [hazelcast/hazelcast-aws#128]
For now, most internal classes are public and maintaining backcompat restricts the scope of changes that we can make which might result in a lot of unwanted mess in the future. 

This is how it looks now:

<img width="335" alt="image" src="https://user-images.githubusercontent.com/2182533/75277801-00d30200-5809-11ea-9705-7bd9def7bee0.png">

Technically, noone should ever depend on them since it's not a part of the public API, but we better hide them then and avoid `sun.misc.Unsafe` situation all over again

**Comment by leszko** [comment]
Fixed during refactoring
