### ISSUE TITLE
TcpIpJoinerOverAWS not considering `hazelcast.tcp.join.port.try.count` parameter

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast-aws#17]
see https://github.com/hazelcast/hazelcast/issues/9640

**Comment by lazerion** [comment]
@mesutcelik I believe we can close it.

**Comment by mesutcelik** [comment]
Was the problem solved? Which PR has solved this problem?

**Comment by lazerion** [comment]
The problem here, as we experienced also in AWS ECS, in order to discovery properly work container must bind to host interface and should be run with `--network=host`, forwarding ports for docker run arguments and eventually scanning will not solve problem.

**Comment by emrahkocaman** [comment]
@mesutcelik Problem is solved with discovery spi implementation. (https://github.com/hazelcast/hazelcast-aws/pull/21/files#diff-27de30b5fa49f4f36e763258a0cd33faR82)

With discovery spi impl, you can use "hz-port" property to start scanning from the desired port.
