### ISSUE TITLE
InvalidConfigurationException: Unknown properties: '[host-reader]' on discovery strategy

### ISSUE THREAD

**Issue by avisecag** [hazelcast/hazelcast-aws#197]
I have been using hazelcast-aws 2.1 for a couple years now to discover cluster instances running on elastic beanstalk. Time has come to update spring-boot, and so we now have hazelcast 3.12.8 running in there, which forced me to update to hazelcast-aws 2.4.
However, when deploying the application to elastic beanstalk, it won't start, because Hazelcast throws an exception during initialisation, which leads to unsatisfied bean shenanigans and early termination in spring-boot. Here's the full exception:

```
com.hazelcast.config.InvalidConfigurationException: Unknown properties: '[host-reader]' on discovery strategy
	at com.hazelcast.spi.discovery.impl.DiscoveryServicePropertiesUtil.verifyNoUnknownProperties(DiscoveryServicePropertiesUtil.java:88) ~[hazelcast-3.12.8.jar!/:3.12.8]
	at com.hazelcast.spi.discovery.impl.DiscoveryServicePropertiesUtil.prepareProperties(DiscoveryServicePropertiesUtil.java:77) ~[hazelcast-3.12.8.jar!/:3.12.8]
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.buildDiscoveryStrategy(DefaultDiscoveryService.java:182) ~[hazelcast-3.12.8.jar!/:3.12.8]
	at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.loadDiscoveryStrategies(DefaultDiscoveryService.java:141) ~[hazelcast-3.12.8.jar!/:3.12.8]
```

My configuration looks like this:
```
private fun Config.configureEc2Discovery(awsProperties: AwsProperties) {
        // enable discovery
        setProperty("hazelcast.discovery.enabled", "true")

        //disable multicast
        val joinConfig = networkConfig.join
        joinConfig.multicastConfig.isEnabled = false

        // Create and configure a discovery strategy
        val factory = AwsDiscoveryStrategyFactory()
        val strategyConfig = DiscoveryStrategyConfig(factory)
        strategyConfig.addProperty("iam-role", awsProperties.iamRole)
        strategyConfig.addProperty("region", awsProperties.region)
        strategyConfig.addProperty("host-reader", awsProperties.hz.hostReader)
        strategyConfig.addProperty("security-group-name", awsProperties.securityGroup)
        strategyConfig.addProperty("tag-key", awsProperties.hz.tagKey)
        strategyConfig.addProperty("tag-value", awsProperties.hz.tagValue)
        strategyConfig.addProperty("hz-port", awsProperties.hz.port)

        // Add the discovery strategy config to the join config.
        joinConfig.discoveryConfig.addDiscoveryStrategyConfig(strategyConfig)
    }
```
I cannot find anything about host-reader being deprecated in the hazelcast-aws documentation. Please advise on how I can get this to run again.

**Comment by leszko** [comment]
What is your `host-reader` value, can you maybe just remove it?

**Comment by avisecag** [comment]
Ah, sorry, should have supplied that right away (though the error gave the impression that hazelcast was not happy about the key, not its value). The value I'm passing to the host-reader is "ec2.amazonaws.com".

I tried just now to simply remove the property, and the application now starts, but it doesn't discover any other instances, although there should be one in the cluster. I'm digging through everything right now to see if this might be due to some ELB configuration issue, but I've already excluded some possibilities.

**Comment by leszko** [comment]
The parameter is actually called `host-header`. I don't remember renaming it from `host-reader`. In any case, you should not need it,  because `ec2.amazonaws.com` is automatically resolved.

**Comment by avisecag** [comment]
Huh... I didn't even notice that when looking at the documentation yesterday. Could have sworn it said host-reader in there. I guess It's possible that the property never actually did anything in my code and the new version of hazelcast is just more vocal about invalid keys being passed to its configuration... :facepalm: 
Thanks a lot for your prompt help. Now I need to figure out why the instances don't discover each other anymore, but I wouldn't expect that to be related.
