### ISSUE TITLE
AWS Lambda support

### ISSUE THREAD

**Issue by redserpent7** [hazelcast/hazelcast-aws#20]
Dears,

Not sure if this is at all possible but I was wondering if you are at least considering add support for AWS lambda.

Regards

**Comment by mesutcelik** [comment]
Hi @redserpent7 ,

What kind of support are you looking for? Reaching Hazelcast Cluster from a Lambda function?

**Comment by redserpent7** [comment]
@mesutcelik yes thats what I'm looking for

**Comment by lazerion** [comment]
Clients can access Cluster from AWS Lambda with Discovery clients, however, there are limitations for [Lambda](http://docs.aws.amazon.com/lambda/latest/dg/limits.html).
