### ISSUE TITLE
AWSConfig getConnectionTimeoutSeconds is not used during connection

### ISSUE THREAD

**Issue by ihsandemir** [hazelcast/hazelcast-aws#22]
It seems like DescribeInstances did not use any timeout during https url connection https://github.com/hazelcast/hazelcast-aws/blob/master/src/main/java/com/hazelcast/aws/impl/DescribeInstances.java#L259 . There is a config parameter set/getConnectionTimeoutSeconds which I expect to be used.

Furthermore, this timeout probably needs to be used for other http requests such as https://github.com/hazelcast/hazelcast-aws/blob/master/src/main/java/com/hazelcast/aws/impl/DescribeInstances.java#L132

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast-aws/pull/30
