### ISSUE TITLE
IMDSv2 support?

### ISSUE THREAD

**Issue by jkern888** [hazelcast/hazelcast-aws#240]
Any plans for adding IMDSv2 support? Details for it at https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html

**Comment by leszko** [comment]
Thanks for creating the GH Issue. I see the following comment.

> Use of Instance Metadata Service Version 2 (IMDSv2) is optional. Instance Metadata Service Version 1 (IMDSv1) will continue to be supported indefinitely.

Do you see any benefit of switching to v2 for Hazelcast AWS Discovery plugin?

**Comment by jkern888** [comment]
It seems to be a security best practice to disable v1 to protect against SSRF attacks

**Comment by leszko** [comment]
I see, so the use case for this would be to allow users who have disabled v1 on their EC2 instances (for security reasons) to use Hazelcast AWS Discovery. TBH so far nobody asked for this feature, so does not seem like a priority to me, but we can implement it at some point.

Also if you would like to contribute, feel free to send a PR.

**Comment by jayhartley** [comment]
We are in the process of rolling our own discovery strategy using v2, because our security team has asked everyone to disable v1. The old version is a favorite target for server-side request forgery (SSRF) attacks because it's fundamentally un-authenticated, and can be used to expose lots of details about the AWS security configuration. See this [AWS security blog post from 2019](https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/).  

I'll see about contributing our work back to this project.

**Comment by jkern888** [comment]
Yea I'm in the same boat @jayhartley. I'll take a look about creating a PR for it, since I believe it's a fairly simple change.

**Comment by leszko** [comment]
Great, thank you both @jayhartley @jkern888 , your contribution is more than welcome :)

**Comment by bravo11** [comment]
Any updates to this? 

A number of companies are moving to enforce IMDSv2. As far as the mention that nobody has asked for this feature, Can I offer up the 15 users of Confluence impacted by this: https://jira.atlassian.com/browse/CONFSERVER-63193

**Comment by jkern888** [comment]
I did end up patching this in locally but it's against the 2.4.x branch so not sure if a PR against that would still be helpful?

**Comment by bravo11** [comment]
It looks like our confluence version is using 3.8.x of hazelcast, Well see how things go next week, I may end up patching locally and then submitting a pr, wouldn't mind seeing what you did in the 2.4.x branch if you can link it

**Comment by jkern888** [comment]
@bravo11 Was a pretty small change. Made a gist of it here https://gist.github.com/jkern888/6e3b7b8046f60f9cdde0814b1d8bf479

**Comment by joedayz** [comment]
Hey guys!! some update about this?  I am using tcp-ip and a list of ip address like workaround because the auto discovery with tags doesn't working.

**Comment by zambien** [comment]
I released a version of @jkern888 gist for folks still on the 2.4 plugin version in my fork:

https://github.com/zambien/hazelcast-aws/releases/tag/v2.4.1

Again, this is just for 2,.4 but seems like a good amount of folks are still using that version.

**Comment by hasancelik** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/23545
