### ISSUE TITLE
Combining ECS/Fargate clusters (for Hazelcast clients) and EC2 Clusters (for Hazelcast cluster members)

### ISSUE THREAD

**Issue by jeanbaptisteguillois** [hazelcast/hazelcast-aws#242]
Hello,

I am trying to configure hazelcast in AWS in the following manner.

I have a cluster of Hazelcast members (using hazelcast 3.11) that is running in a **EC2** set of instances (with an autoscaling group). In this cluster, the **Hazelcast members** successfully discover themselves and it works fine.
I have another cluster of **Hazelcast clients** (using hazelcast 3.11 also) that is running in an **ECS cluster with Fargate** tasks.

The issue I have is that the ECS cluster is not able to connect to the hazelcast members cluster.
I am using this configuration file for the hazelcast clients:

`<hazelcast-client>`
`	<network>`
`		<aws enabled="true">`
`			<hz-port>5701-5799</hz-port>`
`			<region>eu-west-1</region>`
`			<tag-key>Name</tag-key>`
`			<tag-value>MyCluster</tag-value>`
`		</aws>`
`	</network>`
`</hazelcast-client>`

The error message I have in the logs is:
`WARNING: Couldn't connect to the AWS service, [1] retrying in 1 seconds...`

The Fargate task is using an IAM role with a policy giving permissions for ec2:DescribeInstances, ec2:DescribeNetworkInterfaces, ec2:ListTasks.

Any suggestion/direction to help me trouble shoot this error?

Thank you!

PS: I have read the README of this project but I am still confused between ECS and EC2 as well as between Members and clients and the right configuration to pick.

**Comment by leszko** [comment]
You need to explicitly fill your Credentials into the Hazelcast Configuration since the scenario of retrieving credentials from IAM Role in Fargate and connecting to EC2 is not supported atm.

**Comment by jeanbaptisteguillois** [comment]
@leszko thank you, it indeed works well by adding the AWS access keys in the configuration.
