### ISSUE TITLE
Version with "Discovery SPI implementation for AWS" feature does't exists on sonatype repo.

### ISSUE THREAD

**Issue by oleg-vasiliev** [hazelcast/hazelcast-aws#25]
![image](https://cloud.githubusercontent.com/assets/7147660/25385115/9d8db1e0-29cb-11e7-8db6-8e88320d7745.png)
![image](https://cloud.githubusercontent.com/assets/7147660/25385138/b4162492-29cb-11e7-95ff-b362495cdc31.png)

**Comment by emrahkocaman** [comment]
Hi @oleg-vasiliev , the changes are in the master branch, it's not released yet.
Should be out next week. I'd suggest building locally if you want to give it a try.

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast-aws/releases/tag/v2.0.0
