### ISSUE TITLE
README Update for Documentation

### ISSUE THREAD

**Issue by KostaWT** [hazelcast/hazelcast-aws#270]
Hello,

The link to the documentation points to a non existing page:
![image](https://user-images.githubusercontent.com/78849269/155707446-0dc1132d-76aa-4b78-8ad8-5adbc5793b9c.png)
![image](https://user-images.githubusercontent.com/78849269/155707541-485bd7bb-065e-4e1a-9219-8de6ee67b901.png)

**Comment by hasancelik** [comment]
Hi @KostaWT,

Thanks for the issue 👍 

fixed by https://github.com/hazelcast/hazelcast-aws/commit/c103d889e8f7fcfdaa6565a1729b7e4da0e4e7a1
