### ISSUE TITLE
Behavior when tags configured is not available or propagated

### ISSUE THREAD

**Issue by mesutcelik** [hazelcast/hazelcast-aws#28]
We need to define a behavior if tags can't be retrieved for some period of time and fail fast at the end if tag can't be resolved.

see the issue -->  https://github.com/hazelcast/hazelcast/issues/10537

**Comment by lazerion** [comment]
@mesutcelik we added configurable `timeout` for queries. I believe we can close this issue.

**Comment by mesutcelik** [comment]
Can you please reference the PR here?

**Comment by emrahkocaman** [comment]
Closing this issue, resolved by https://github.com/hazelcast/hazelcast-aws/pull/30. ([This line](https://github.com/hazelcast/hazelcast-aws/pull/30/files#diff-81b776ac33a4d0d722dde3ec4d9377e3R286) to be specific.)

**Comment by dimas** [comment]
Chaps, are you sure the original issue is resolved by this PR?
This comment https://github.com/hazelcast/hazelcast/issues/10537#issuecomment-302733138 explains how I see it - the important bit is not what timeout you have for AWS HTTP requests but how do you make sure if AWS response is good to use. (If the node cannot see itself in the response, it is probably not too early to trust that response - tags has not propagated yet...)

**Comment by mesutcelik** [comment]
I am reopening the issue. You basically say we need to retry if we see empty list [here](https://github.com/hazelcast/hazelcast-aws/blob/v2.1.0/src/main/java/com/hazelcast/aws/AwsDiscoveryStrategy.java#L147). It has to return at least itself in case of a single-member or first member case.

**Comment by dimas** [comment]
Yes, correct.
Thank you.
In our custom scripts we run before starting Hazelcast we do do not check that node can find itself, we only check if list is empty or not. Even if the node cannot find itself it is probably ok as long as it sees another one - it will try to cluster with it.

**Comment by leszko** [comment]
Moving the discussion started in #64 . Last comment from Mesut: "empty means to me either tags are not propagated as described in #28 or there is no tag configured although they are defined in hazelcast config.
It is good idea to move the discussion to #28"

**Comment by mesutcelik** [comment]
The original issues created is https://github.com/hazelcast/hazelcast/issues/10537#issue-227485890 and the delay mechanism that is used by @dimas was probably because they didn't want to see temporary Split Brain.

@dimas Can you please comment on this?

**Comment by leszko** [comment]
Closing  due to inactivity.
