### ISSUE TITLE
AWS discovery does not have member port configuration for clients

### ISSUE THREAD

**Issue by sertugkaya** [hazelcast/hazelcast-aws#3]
Currently, with version 3.6 using aws discovery, clients only try to connect port 5701, 5702 and 5703. If one configures members on different ports than these, clients are not able to find members on aws.

**Comment by emrahkocaman** [comment]
@sertugkaya hazelcast-aws plugin now implements Discovery SPI. You can define the member port using `hz-port` property. See [documentation](https://github.com/hazelcast/hazelcast-aws#configuring-aws-discovery-using-discovery-spi-for-hazelcast-client) for details.
This will be available with the next release of hazelcast-aws.
