### ISSUE TITLE
connection-timeout-seconds command rejected

### ISSUE THREAD

**Issue by sshorkey** [hazelcast/hazelcast-aws#33]
Attempting to start up hazelcast has resulted in this error:
`Caused by: com.hazelcast.config.InvalidConfigurationException: cvc-complex-type.2.4.a: Invalid content was found starting with element 'connection-timeout-seconds'. One of '{"http://www.hazelcast.com/schema/config":iam-role, "http://www.hazelcast.com/schema/config":host-header, "http://www.hazelcast.com/schema/config":tag-key, "http://www.hazelcast.com/schema/config":tag-value}' is expected.`

**Comment by sshorkey** [comment]
```
            <aws enabled="true">
                <access-key>(redacted)</access-key>
                <secret-key>(redacted)</secret-key>
                <!--optional, default is us-east-1 -->
                <region>us-east-1</region>
                <security-group-name>(redacted)</security-group-name>
                <connection-timeout-seconds>60</connection-timeout-seconds>
            </aws>

```

**Comment by mesutcelik** [comment]
Thx for the quick feedback. Can you please try as an attribute to `aws` tag.
 `<aws enabled="true" connection-timeout-seconds="60" >`

**Comment by sshorkey** [comment]
Solved the problem. Thanks.

**Comment by mesutcelik** [comment]
good to hear that!

We highly recommend to use Discovery SPI based configuration for future. please see the [README](https://github.com/hazelcast/hazelcast-aws) 
We will remove the support for the old configuration in future. cc: @mmedenjak

**Comment by mmedenjak** [comment]
The old `aws` element will definitely be removed in hazelcast 4.0, I suggest you try out the discovery SPI version until then.
