### ISSUE TITLE
Discovery SPI not working between Client and Cluster

### ISSUE THREAD

**Issue by ashwinivin** [hazelcast/hazelcast-aws#38]
Getting the Following error when trying to connect to the client in AWS. Below is the error log: Any help would be greatly appreciated.

`Aug 07, 2017 6:03:13 PM com.hazelcast.client.config.XmlClientConfigLocator
INFO: Loading configuration /home/ec2-user/hazelcast-client-config.xml from System property 'hazelcast.client.config'
Aug 07, 2017 6:03:13 PM com.hazelcast.client.config.XmlClientConfigLocator
INFO: Using configuration file at /home/ec2-user/hazelcast-client-config.xml
Aug 07, 2017 6:03:13 PM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [cerberus-dev] [3.8.3] HazelcastClient 3.8.3 (20170704 - 10e1449) is STARTING
Aug 07, 2017 6:03:13 PM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [cerberus-dev] [3.8.3] HazelcastClient 3.8.3 (20170704 - 10e1449) is STARTED
Aug 07, 2017 6:03:13 PM com.hazelcast.client.spi.impl.ClusterListenerSupport
INFO: hz.client_0 [cerberus-dev] [3.8.3] Trying to connect to [127.0.0.1]:5703 as owner member
Aug 07, 2017 6:03:13 PM com.hazelcast.client.spi.impl.ClusterListenerSupport
WARNING: hz.client_0 [cerberus-dev] [3.8.3] Exception during initial connection to localhost/127.0.0.1:5703, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused
Aug 07, 2017 6:03:13 PM com.hazelcast.client.spi.impl.ClusterListenerSupport
INFO: hz.client_0 [cerberus-dev] [3.8.3] Trying to connect to [127.0.0.1]:5701 as owner member
Aug 07, 2017 6:03:13 PM com.hazelcast.client.spi.impl.ClusterListenerSupport
WARNING: hz.client_0 [cerberus-dev] [3.8.3] Exception during initial connection to localhost/127.0.0.1:5701, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused
Aug 07, 2017 6:03:13 PM com.hazelcast.client.spi.impl.ClusterListenerSupport
INFO: hz.client_0 [cerberus-dev] [3.8.3] Trying to connect to [127.0.0.1]:5702 as owner member
Aug 07, 2017 6:03:13 PM com.hazelcast.client.spi.impl.ClusterListenerSupport
WARNING: hz.client_0 [cerberus-dev] [3.8.3] Exception during initial connection to localhost/127.0.0.1:5702, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused
Aug 07, 2017 6:03:13 PM com.hazelcast.client.spi.impl.ClusterListenerSupport
WARNING: hz.client_0 [cerberus-dev] [3.8.3] Unable to get alive cluster connection, try in 2935 ms later, attempt 1 of 2.
Aug 07, 2017 6:03:16 PM com.hazelcast.client.spi.impl.ClusterListenerSupport
INFO: hz.client_0 [cerberus-dev] [3.8.3] Trying to connect to [127.0.0.1]:5703 as owner member
Aug 07, 2017 6:03:16 PM com.hazelcast.client.spi.impl.ClusterListenerSupport
WARNING: hz.client_0 [cerberus-dev] [3.8.3] Exception during initial connection to localhost/127.0.0.1:5703, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused
Aug 07, 2017 6:03:16 PM com.hazelcast.client.spi.impl.ClusterListenerSupport
INFO: hz.client_0 [cerberus-dev] [3.8.3] Trying to connect to [127.0.0.1]:5702 as owner member
Aug 07, 2017 6:03:16 PM com.hazelcast.client.spi.impl.ClusterListenerSupport
WARNING: hz.client_0 [cerberus-dev] [3.8.3] Exception during initial connection to localhost/127.0.0.1:5702, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused
Aug 07, 2017 6:03:16 PM com.hazelcast.client.spi.impl.ClusterListenerSupport
INFO: hz.client_0 [cerberus-dev] [3.8.3] Trying to connect to [127.0.0.1]:5701 as owner member
Aug 07, 2017 6:03:16 PM com.hazelcast.client.spi.impl.ClusterListenerSupport
WARNING: hz.client_0 [cerberus-dev] [3.8.3] Exception during initial connection to localhost/127.0.0.1:5701, exception com.hazelcast.core.HazelcastException: java.net.ConnectException: Connection refused
Aug 07, 2017 6:03:16 PM com.hazelcast.client.spi.impl.ClusterListenerSupport
WARNING: hz.client_0 [cerberus-dev] [3.8.3] Unable to get alive cluster connection, try in 2997 ms later, attempt 2 of 2.
Aug 07, 2017 6:03:19 PM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [cerberus-dev] [3.8.3] HazelcastClient 3.8.3 (20170704 - 10e1449) is SHUTTING_DOWN
Aug 07, 2017 6:03:19 PM com.hazelcast.core.LifecycleService
INFO: hz.client_0 [cerberus-dev] [3.8.3] HazelcastClient 3.8.3 (20170704 - 10e1449) is SHUTDOWN
Exception in thread "main" java.lang.IllegalStateException: Unable to connect to any address in the config! The following addresses were tried: [localhost/127.0.0.1:5701, localhost/127.0.0.1:5702, localhost/127.0.0.1:5703]
	at com.hazelcast.client.spi.impl.ClusterListenerSupport.connectToCluster(ClusterListenerSupport.java:178)
	at com.hazelcast.client.spi.impl.ClientClusterServiceImpl.start(ClientClusterServiceImpl.java:189)
	at com.hazelcast.client.impl.HazelcastClientInstanceImpl.start(HazelcastClientInstanceImpl.java:403)
	at com.hazelcast.client.HazelcastClientManager.newHazelcastClient(HazelcastClientManager.java:78)
	at com.hazelcast.client.HazelcastClient.newHazelcastClient(HazelcastClient.java:72)
	at com.capitalone.cerberus.GettingStartedClient.main(GettingStartedClient.java:19)`

**Comment by ashwinivin** [comment]
The settings.XML file is attached below:
`<hazelcast-client xsi:schemaLocation="http://www.hazelcast.com/schema/client-config hazelcast-client-config-3.8.xsd"
           xmlns="http://www.hazelcast.com/schema/client-config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

<license-key>"Removing it due to privacy"</license-key>

  <group>
    <name>"Removing it due to Privacy"</name>
    <password>"Removing it due to privacy"</password>
  </group>

 <properties>
    <property name="hazelcast.discovery.enabled">true</property>
</properties>

  <network>

<discovery-strategies>
        
        <discovery-strategy enabled="true" class="com.hazelcast.aws.AwsDiscoveryStrategy">
            <properties>
               <property name="iam-role">Removing due to Privacy</property>
               <property name="tag-key">type</property>
               <property name="tag-value">dev-cerb-powderkeg-hz-nodes</property>
               <property name="hz-port">11415</property>
               <property name="connection-timeout-seconds">30</property>
            </properties>
        </discovery-strategy>
     </discovery-strategies>
  </network>
 </hazelcast-client>
`

**Comment by ashwinivin** [comment]
Any help is greatly appreciated.

**Comment by lazerion** [comment]
@ashwinivin could you please check `cp` or `CLASSPATH` it seems that HZ discovery plugin is not loaded.

**Comment by mesutcelik** [comment]
Hi @ashwinivin , 
There were some issues with java client in AWS env. Can you please try it with the latest java client which is 3.9.1 for the time being?

I am closing this issue. please feel free to reopen if you are still experiencing the problem.
