### ISSUE TITLE
Not able to start in cluster mode without access-key and secret-key

### ISSUE THREAD

**Issue by vigneshsenapathy** [hazelcast/hazelcast-aws#43]
hey guys,

I am trying to start orientdb using the hazelcast-aws. I have my hazelcast.xml which doesnt have a access-key and secret key. I have a i-am role which has access to ec2 and it complains it needs a access-key 

Error log:
accessKey must contain text

My hazelcast.xml looks like this 

<?xml version="1.0" encoding="UTF-8"?>
<hazelcast id="hazelcast-consul-discovery" 
           xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.6.xsd"
           xmlns="http://www.hazelcast.com/schema/config"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

    <properties>
      <property name="hazelcast.discovery.enabled">true</property>      
    </properties>

    <network>        
        <join>
            <multicast enabled="false"/>
            <aws enabled="false"/>
            <tcp-ip enabled="false"/>
              
             <discovery-strategies>
                <discovery-strategy enabled="true" class="com.hazelcast.aws.AwsDiscoveryStrategy">
                  <properties>
                    <property name="access-key"></property>
                    <property name="secret-key"></property>
                    <property name="iam-role">testing</property>
                    <property name="region">us-east-1</property>
                    <property name="tag-key">something</property>
                    <property name="tag-value">something</property>
                    <property name="connection-timeout-seconds">30</property>
                    <property name="hz-port">5701</property>
                  </properties>
                </discovery-strategy>
             </discovery-strategies>
              
        </join>
    </network>
</hazelcast>

Please let me know if i am doing something wrong

**Comment by mesutcelik** [comment]
Hi @vigneshsenapathy ,

This is already [fixed](https://github.com/hazelcast/hazelcast-aws/issues/32) and will be released in hazelcast-aws 2.1. 
You can only build the jar from master branch and use it for the time being.

**Comment by vigneshsenapathy** [comment]
@mesutcelik : so i build the jar out of master i should be ok to use it right ?

**Comment by mesutcelik** [comment]
@vigneshsenapathy 

We don't recommend that normally so if you see a risk don't use it from snapshot...
You can also wait hazelcast-aws 2.1 release which is probably this week or next week so that you can directly use it from Maven Central

**Comment by vigneshsenapathy** [comment]
@mesutcelik : cool. For now i will use the key and i will wait for the one to be pushed to maven central.
