### ISSUE TITLE
How do I configure the AwsDiscoveryStrategy programmatically ?

### ISSUE THREAD

**Issue by tal181** [hazelcast/hazelcast-aws#45]
InterfacesConfig interfacesConfig = new InterfacesConfig();
            interfacesConfig.setEnabled(true);
            List interface1 = new ArrayList<>();
            interface1.add("10.0.*.*");
            interfacesConfig.setInterfaces(interface1);
            network.setInterfaces(interfacesConfig);

            //set aws discovery
            Map<String, Comparable> properties = new HashMap<String, Comparable>();
            properties.put("access-key", awsAccessKeyId);
            properties.put("secret-key", awsSecretAccessKey);
            properties.put("iam-role", "aaaa");
            //properties.put("region",awsSecretAccessKey); //Default value is us-east-1
            properties.put("host-header", "ec2.amazonaws.com");
            properties.put("security-group-name", "hazelcast");
            properties.put("tag-key", "aa-cluster");
            properties.put("tag-value", "aa-cluster");
            properties.put("hz-port", port.toString());

            DiscoveryStrategyConfig discoveryStrategyConfig = new DiscoveryStrategyConfig("AwsDiscoveryStrategy",properties);
          
            DiscoveryConfig discoveryConfig = new DiscoveryConfig();
            discoveryConfig.addDiscoveryStrategyConfig(discoveryStrategyConfig);
            join.setDiscoveryConfig(discoveryConfig);

Is this is the correct why to configure the AwsDiscoveryStrategy ?

Thanks,
Tal

**Comment by mesutcelik** [comment]
Hi @tal181 ,

I think you should use full classname `com.hazelcast.aws.AwsDiscoveryStrategy` and you don't have to give both `iam-role` and `access-key`/`secret-key` pair at the same time.

**Comment by mesutcelik** [comment]
I hope your problem is resolved now.
please do not hesitate to ask future questions to [Hazelcast Google Groups](https://groups.google.com/forum/#!forum/hazelcast)
