### ISSUE TITLE
why do I have to use access key and secret key for cluster member discovery

### ISSUE THREAD

**Issue by yinhua-dai** [hazelcast/hazelcast-aws#46]
Hi,

I am running several applications running in different ec2s, and all these applications should compose to a hazelcast cluster, no cluster client.

When I am trying the auto discovery function, I found that access key and secret key must be specified, can't they use EC2 default authentication as they are already running inside AWS.

Thanks.

**Comment by mesutcelik** [comment]
Hi @yinhua-dai,
Thanks for the heads up!

This is actually fixed in master and will be available in maven as version 2.1 in a few days.
please see https://github.com/hazelcast/hazelcast-aws/issues/32
