### ISSUE TITLE
ZONE_AWARE partition group only work with Discovery SPI and not doc. about that wont work work with `aws` tag config

### ISSUE THREAD

**Issue by gokhanoner** [hazelcast/hazelcast-aws#47]
From Node.js

```
        if (properties.getBoolean(DISCOVERY_SPI_ENABLED)) {
            discoveryService.start();

            // Discover local metadata from environment and merge into member attributes
            mergeEnvironmentProvidedMemberMetadata();
        }
```

So if AWS is configured the old way, then `mergeEnvironmentProvidedMemberMetadata` methods not called and this causes PARTITION_GROUP_ZONE info not being populated: https://github.com/hazelcast/hazelcast-aws/blob/master/src/main/java/com/hazelcast/aws/AwsDiscoveryStrategy.java#L118

Since `aws` tag is deprecated, this seems normal but please at least add a doc to READ.me that ZONE_AWARE partition group works only SPI, not with `aws` tags.

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast-aws/commit/42d156369a9f66b3ce3f3ab807931412fe91cec7

Thanks @gokhanoner !
