### ISSUE TITLE
List of recommended ec2 instances is out of date

### ISSUE THREAD

**Issue by bfeldkamp3** [hazelcast/hazelcast-aws#49]
https://github.com/hazelcast/hazelcast-aws#selecting-ec2-instance-type

This list is outdated and lists some deprecated instances and doesn't list some newer instances.

Here's the list of current instances - https://aws.amazon.com/ec2/instance-types/

Is this just a matter of listing all instances that have 10GB+ or High under the `Networking Performance` category?

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast-aws/commit/4468e9286f791ebddf399987462d6a96c6034a51 
Thx @bfeldkamp3 for the heads up!

> Is this just a matter of listing all instances that have 10GB+ or High under the Networking Performance category?
correct!
