### ISSUE TITLE
Configuring AwsDiscoveryStrategy  programaticly

### ISSUE THREAD

**Issue by polanskya** [hazelcast/hazelcast-aws#53]
Could you please provide samples how to configure AwsDiscoveryStrategy programmatically?

Thanks

**Comment by hasancelik** [comment]
Hi @polanskya ,

Here is the example instance/server config:

```
        Config config = new Config();
        config.getProperties().setProperty("hazelcast.discovery.enabled", "true");
        AwsDiscoveryStrategyFactory awsDiscoveryStrategyFactory = new AwsDiscoveryStrategyFactory();
        Map<String, Comparable> properties = new HashMap<String, Comparable>();
        .... put your properties into map ....
        DiscoveryStrategyConfig discoveryStrategyConfig = new DiscoveryStrategyConfig(awsDiscoveryStrategyFactory, properties);
        config.getNetworkConfig().getJoin().getDiscoveryConfig().addDiscoveryStrategyConfig(discoveryStrategyConfig);
        HazelcastInstance instance = Hazelcast.newHazelcastInstance(config);
```

As a side note, you need to add the hazelcast-aws.jar dependency to your project.

**Comment by mesutcelik** [comment]
@hasancelik 
Can we add a sample to https://github.com/hazelcast/hazelcast-code-samples ?

**Comment by hasancelik** [comment]
@mesutcelik 

I have created [PR](#54 ) which updates README with programmatic configuration snippets and also I have created [issue](https://github.com/hazelcast/hazelcast-code-samples/issues/210) at code samples repo.

**Comment by hasancelik** [comment]
Hi @polanskya ,

Did config that I shared work for your setup?

**Comment by googlielmo** [comment]
Provided by #54. Looks like we can close this issue.

**Comment by polanskya** [comment]
Yes.. sorry for delay response .. worked great.. I am running this on 2 instance Beanstalk at the moment..  

I would like to share how to automatically get some of the AWS properties using AWS Sdk, perhaps this can be added to examples.. 
import com.amazonaws.AmazonClientException;
import com.amazonaws.services.ec2.AmazonEC2;
import com.amazonaws.services.ec2.AmazonEC2Client;
import com.amazonaws.services.ec2.model.DescribeTagsRequest;
import com.amazonaws.services.ec2.model.DescribeTagsResult;
import com.amazonaws.services.ec2.model.Filter;
import com.amazonaws.util.EC2MetadataUtils;

public static final String ELASTICBEANSTALK_EC2_ROLE_NAME = "aws-elasticbeanstalk-ec2-role";
	public static final String ELASTICBEANSTALK_ENV_TAG_KEY = "elasticbeanstalk:environment-name";

	protected Map<String, Comparable> getAwsConfigProps() {

		AmazonEC2 amazonEC2 = null;
		try {
			amazonEC2 = AmazonEC2Client.builder().build();
		} catch (AmazonClientException ace) {
			log.error("Couldn't authenticate with AWS; local cluster configuration will be used.", ace);
		}
		EC2MetadataUtils.InstanceInfo instanceInfo = EC2MetadataUtils.getInstanceInfo();
		String instanceId = instanceInfo.getInstanceId();

		// EB sets the environment ID and name as the elasticbeanstalk:environment-id
		// and
		// elasticbeanstalk:environment-name EC2 tags on all of the parts of an EB app
		// environment: load balancer,
		// EC2 instances, security groups, etc. Surprisingly, EC2 tags aren't available
		// to instances through the
		// instance metadata interface, but they are available through the normal AWS
		// API’s DescribeTags call.
		Collection<Filter> filters = new ArrayList<Filter>();

		filters.add(new Filter("resource-type").withValues("instance"));
		filters.add(new Filter("resource-id").withValues(instanceId));
		filters.add(new Filter("key").withValues(ELASTICBEANSTALK_ENV_TAG_KEY));

		DescribeTagsRequest describeTagsRequest = new DescribeTagsRequest();
		describeTagsRequest.setFilters(filters);
		DescribeTagsResult describeTagsResult = amazonEC2.describeTags(describeTagsRequest);

		// describeTagsResult.getTags().forEach((tag) ->
		// System.out.println(tag.toString()));

		String environmentName = describeTagsResult.getTags().get(0).getValue();
		Map<String, Comparable> properties = new HashMap<String, Comparable>();

		properties.put("region", instanceInfo.getRegion());
		properties.put("tag-key", ELASTICBEANSTALK_ENV_TAG_KEY);
		properties.put("tag-value", environmentName);
		properties.put("iam-role", ELASTICBEANSTALK_EC2_ROLE_NAME);

		amazonEC2.shutdown();

		return properties;
	}

Gradle dependency i am using: 

aws_java_sdk_version=1.11.257
hazelcast_version=3.9.2
hazelcast_aws_version=2.1.0
hazelcast_hibernate52_version=1.2.2


    compile "com.hazelcast:hazelcast:${hazelcast_version}"
    compile "com.hazelcast:hazelcast-hibernate52:${hazelcast_hibernate52_version}"
    compile "com.hazelcast:hazelcast-spring:${hazelcast_version}"
    compile "com.hazelcast:hazelcast-aws:${hazelcast_aws_version}"
    compile "com.amazonaws:aws-java-sdk-ec2:${aws_java_sdk_version}"
    compile "com.amazonaws:aws-java-sdk-core:${aws_java_sdk_version}"

Thanks for your help!
