### ISSUE TITLE
Can the plugin work with network mode as bridge

### ISSUE THREAD

**Issue by vigneshsenapathy** [hazelcast/hazelcast-aws#55]
Hi,

I am trying to use the hazelcast-aws plugin and wanted to know if it can work in network mode as bridge? Please let me know if this is possible
Below is the text from the your document which says that the bind should be in host mode

Configuring Hazelcast Cluster Members for AWS ECS
In order to enable discovery within AWS ECS Cluster, within taskdef.json or container settings, Hazelcast member should be bind to host network. Therefore, proper json representation for task should contain below segment:

"networkMode": "host"

Thanks,

Vignesh

**Comment by hasancelik** [comment]
Hi @vigneshsenapathy ,

Unfortunately, current implementation of this plugin does not support bridge network. If you want to use this discovery plugin on ECS cluster, hazelcast member should be bind to host network.

**Comment by googlielmo** [comment]
Closing this as the original question was answered. Feel free to open other issues for more questions.
