### ISSUE TITLE
Discovery config for AWS does not warn/abort on unknown properties being specified in config

### ISSUE THREAD

**Issue by vertex-github** [hazelcast/hazelcast-aws#58]
Add an unknown property to the configuration for AWS discovery (client or server).  Unknown props are silently ignored - which for the case of a typo is not helpful.

**Comment by leszko** [comment]
This change needs to be done in Hazelcast Core (https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/spi/discovery/impl/DefaultDiscoveryService.java#L195). 

Therefore:
1) It will affect all Service Discovery Plugins (not only AWS)
2) It won't be backward compatible, however will be harmful only if an unused parameter is available in config at the moment (then the upgrade to the new version will block hazelcast member to start-up, the solution is to fix XML or Config object - the former breaks the binary compatibility).

@mmedenjak , do you think we can release such change in 3.10.x?

**Comment by mmedenjak** [comment]
Yes, it's possible to add in a patch release. I don't see this as a critical issue though and we will see if we have time to implement it.

**Comment by mesutcelik** [comment]
@mmedenjak I think Rafal was asking if we can make it into 3.10... He will provide the PR.... 

@vertex-github We realized that this is a hazelcast core change and I don't think this can be added to 3.9.4 because it is breaking backward compatibility of Discovery SPI

**Comment by leszko** [comment]
yes, I'll prepare a PR.

I'll add you both (@mmedenjak @mesutcelik) as reviewers.

**Comment by mmedenjak** [comment]
Sure, we can merge it whenever it is ready

**Comment by mesutcelik** [comment]
fixed by https://github.com/hazelcast/hazelcast/pull/12819
