### ISSUE TITLE
Support for AWS ElasticBeanstalk EC2 Instances.

### ISSUE THREAD

**Issue by pkgonan** [hazelcast/hazelcast-aws#69]
Hi
I think that It is not working.
It can not detect other EC2 Instance on AWS ElasticBeanstalk.
And can not clustering.

// Log message

    Members {size:1, ver:1} [
	Member [10.0.0.234]:5701 - 8fb81705-4afa-4753-bda6-5a2d97f9ee0f this
    ]

    Members {size:1, ver:1} [
	Member [10.0.0.234]:5702 - f01ca206-a534-40a0-aff0-830c68d13d4a this
    ]

    Dropped: SplitBrainJoinMessage{packetVersion=4, buildNumber=20180424, 
    memberVersion=3.10.0, clusterVersion=3.10, address=[10.0.0.203]:5702, uuid=‘b6aa90a0-b6e7- 
    4c59-82d6-c920ba55d9c8’, liteMember=false, memberCount=1, dataMemberCount=1, 
    memberListVersion=1}

    // My Settings..

    import com.hazelcast.aws.AwsDiscoveryStrategyFactory;
    import com.hazelcast.config.*;
    import com.hazelcast.core.HazelcastInstance;
    import com.hazelcast.instance.HazelcastInstanceFactory;
    import com.hazelcast.spring.cache.HazelcastCacheManager;
    import org.springframework.beans.factory.annotation.Value;
    import org.springframework.cache.CacheManager;
    import org.springframework.cache.annotation.EnableCaching;
    import org.springframework.context.annotation.Bean;
    import org.springframework.context.annotation.Configuration;

    import java.util.ArrayList;
    import java.util.HashMap;
    import java.util.Map;

    @enablecaching
    @configuration
    public class HazelcastConfig {

    private static final String TAG_KEY = "elasticbeanstalk:environment-name";

    @Value("${aws.environment-name")
    private String environmentName;

    @Value("${aws.region}")
    private String region;

    @Value("${aws.access-key}")
    private String accessKey;

    @Value("${aws.secret-key}")
    private String secretKey;

    @Bean
    public Config config() {
        Config config = new Config();

        config.setInstanceName("Hazelcast-Instance");

        // EC2  Discovery true
        config.getProperties().setProperty("hazelcast.discovery.enabled", "true");

        // ZONE
        PartitionGroupConfig partitionGroupConfig = config.getPartitionGroupConfig();
        partitionGroupConfig
                .setEnabled(true)
                .setGroupType(PartitionGroupConfig.MemberGroupType.ZONE_AWARE);
        config.setPartitionGroupConfig(partitionGroupConfig);

       
        JoinConfig joinConfig = config.getNetworkConfig().getJoin();
        joinConfig.getTcpIpConfig().setEnabled(false);
        joinConfig.getMulticastConfig().setEnabled(false);
        joinConfig.getAwsConfig().setEnabled(false);

        // EC2  Discovery 
        AwsDiscoveryStrategyFactory awsDiscoveryStrategyFactory = new AwsDiscoveryStrategyFactory();
        Map<String, Comparable> properties = new HashMap<>();
        properties.put("access-key", accessKey);
        properties.put("secret-key", secretKey);
        properties.put("region", region);
        properties.put("host-header", "ec2.amazonaws.com");
        properties.put("tag-key", TAG_KEY);
        properties.put("tag-value", environmentName);
        properties.put("connection-timeout-seconds", "5");
        properties.put("hz-port","5701");

        DiscoveryStrategyConfig discoveryStrategyConfig = new 
        DiscoveryStrategyConfig(awsDiscoveryStrategyFactory, properties);
        joinConfig.getDiscoveryConfig().addDiscoveryStrategyConfig(discoveryStrategyConfig);

        ArrayList<DiscoveryStrategyConfig> discoveryStrategyConfigs = new ArrayList<>();
        joinConfig.getDiscoveryConfig().setDiscoveryStrategyConfigs(discoveryStrategyConfigs);

        // Cache Map
        MapConfig mapConfig = new MapConfig()
                .setName("cache")
                .setMaxSizeConfig(new MaxSizeConfig(200, MaxSizeConfig.MaxSizePolicy.FREE_HEAP_SIZE))
                .setEvictionPolicy(EvictionPolicy.LRU)
                .setTimeToLiveSeconds(20)
                .setNearCacheConfig(new NearCacheConfig());
        config.addMapConfig(mapConfig);

        // Cache ManagementCenter
        ManagementCenterConfig managementCenterConfig = new ManagementCenterConfig()
                .setEnabled(true)
                .setUrl("http://localhost:8080/mancenter")
                .setUpdateInterval(3);
        config.setManagementCenterConfig(managementCenterConfig);

        return config;
        }

        @Bean
        public HazelcastInstance hazelcastInstance() {
            return HazelcastInstanceFactory.newHazelcastInstance(config());
        }

        @Bean
        public CacheManager cacheManager() {
            return new HazelcastCacheManager(hazelcastInstance());
        }
    }

Please let me know if it works with Elastic Beanstalk.
I want to use Spring boot data jpa + AWS Beanstalk +Hazelcast Second level cache

    -----------------------------------------
    <dependency>
      <groupId>com.hazelcast</groupId>
      <artifactId>hazelcast-spring</artifactId>
      <version>3.10</version>
    </dependency>
    <dependency>
      <groupId>com.hazelcast</groupId>
      <artifactId>hazelcast-hibernate52</artifactId>
      <version>1.2.3</version>
    </dependency>
    <dependency>
      <groupId>com.hazelcast</groupId>
      <artifactId>hazelcast-aws</artifactId>
      <version>2.1.1</version>
    </dependency>

     -----------------------------------------

    properties:
    hibernate.format_sql: true
    hibernate.dialect: org.hibernate.dialect.MariaDBDialect
    hibernate.cache.use_second_level_cache: true
    hibernate.cache.use_query_cache: true
    hibernate.cache.use_minimal_puts: true
    hibernate.cache.region.factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory

**Comment by leszko** [comment]
Hi @pkgonan,

Thank for reporting it. We'll check that.

**Comment by mesutcelik** [comment]
Hi @pkgonan 
We actually did not test hazelcast-aws in AWS ElasticBeanstalk Environment so I can't judge the effort required. However, your contributions would be very welcome in this.

**Comment by pkgonan** [comment]
@leszko
@mesutcelik

Hi, I would like to use hazelcast in AWS Beanstalk environment.
Is there another alternative to use?

**Comment by mesutcelik** [comment]
Hazelcast is not tested in AWS Beanstalk env. 
please feel free to test and provide feedback.

You can also use hazelcast in kubernetes env. too 
please check for more info.
https://github.com/hazelcast/hazelcast-kubernetes

**Comment by feanor07** [comment]
I tested and used `aws elastic beanstalk` via deploying a relatively simple application. It worked fine. One thing I need to mention is that you need to ensure security groups you use allow inbound traffic for ports hazelcast is relying on.

**Comment by mesutcelik** [comment]
@feanor07 Tesekkurler!

It would be useful for others if you share you codesample on github so that other people can benefit from it.
The other option is to write a guide that will be hosted by hazelcast but not sure how to automate integration testing with Elasticbeanstalk to check the validity of the guide over time.

https://github.com/hazelcast-guides/base-guide/wiki/How-to-write-a-guide

**Comment by feanor07** [comment]
@mesutcelik planning on writing a small how-to article if I find some time soon. I will post it to here when I am don 🤞

**Comment by jklingsporn** [comment]
@feanor07 If you have the time, can you please explain to me how you did it (just some bullet points)? Like any deviations from the default configuration? I am trying to configure it defining an IAM-role and using tags. I've also setup the security groups to allow any TCP communication on any port and provided the IAM-role with the necessary EC2-permissions but without luck. Your help would be really appreciated.

**Comment by jklingsporn** [comment]
Just a quick update: when I disable aws-discovery for the nodes that are lite-members and enable tcp-id with a fixed ip, everything works like a charm.

**Comment by jklingsporn** [comment]
@feanor07 our configuration has some issues regarding resilience. Let's say AWS decides to replace our only know instance with another machine, our whole cluster will die. Also, when we have to reboot the known cluster-member we have to reboot all other nodes as well in order to have a working cluster.

**Comment by leszko** [comment]
@jklingsporn I think you need to change the Deployment policy to `Rolling`. Otherwise, you kill all Hazelcast members at once, and therefore the cluster is down and loses data.

I tested Hazelcast on AWS Elastic Beanstalk and it works correctly. I added a description in this PR: https://github.com/hazelcast/hazelcast-aws/pull/207. It should close this issue. I suggest opening new GH issues with more precise steps to reproduce if anyone encounters any problem with the Beanstalk environment.
