### ISSUE TITLE
Change implementation of <aws> to discovery strategy

### ISSUE THREAD

**Issue by leszko** [hazelcast/hazelcast-aws#74]
Currently there are two implementations of AWS Discovery:
- `<aws>` (deprecated) - implemented in Hazelcast Root
- SPI Discovery Strategy - implemented in Hazelcast AWS

The underlying implementation of `<aws>` should be changed to SPI.

Note: Most of this issue will have to be implemented in Hazelcast Root.

**Comment by dbrimley** [comment]
So you're suggesting that the <aws> configuration elements remains right?

**Comment by leszko** [comment]
Yes, this issue is to change the underlying implementation.

**Comment by mesutcelik** [comment]
I consider this as a cleanup with backward compatibility guaranteed because it does not make sense to maintain `TcpIpJoinerOverAWS` while we have Discovery SPI Implementation.

**Comment by dbrimley** [comment]
Ok, I'm fine with that.
