### ISSUE TITLE
Problem Configuring Hazelcast Members for AWS ECS 

### ISSUE THREAD

**Issue by philmath-pea** [hazelcast/hazelcast-aws#77]
Following the instruction and I get this error which seems to directly contradict the readme. 

> '10.0.*.* ' is not an IP address! Removing from interface list.

I'm using the NetworkConfig class to configure instead of hazelcast.xml file. 

```
if (properties.isInterfacesEnable()) {
            InterfacesConfig interfacesConfig = new InterfacesConfig()
                    .setEnabled(properties.isInterfacesEnable())
                    .addInterface(properties.getInterfacesSubnet());
            networkConfig.setInterfaces(interfacesConfig);
        }
```

**Comment by leszko** [comment]
@philmath-pea ,

What are the private IP addresses of the EC2 instances backing up  your ECS cluster? You may have them in a different network and then you'd need to specify something different, for example:

```
<interfaces enabled="true">
    <interface>192.168.*.*</interface>
</interfaces>
```

**Comment by philmath-pea** [comment]
all 6 servers in the cluster are in 10.0.10.*

**Comment by leszko** [comment]
Could you paste here your `hazelcast.xml` and the Hazelcast version that you use?

**Comment by philmath-pea** [comment]
I'm not using a hazelcast.xml . the code above is how I'm configuring hazel cast. Version 3.7

**Comment by leszko** [comment]
I see, it should work. A few things more that you can check:

1. The output message is interesting, because `10.0..` does not contain `*`. Could you check that the value you pass to the configuration is exactly `10.0.*.*`?
2. You can try `hazelcast.xml` and if it works and exactly the same configuration fails for the Java-based config, then report a bug in https://github.com/hazelcast/hazelcast
3. You can try updating to the most recent Hazelcast version.

**Comment by leszko** [comment]
@philmath-pea , so If I understand correctly you still have an issue but `No EC2 instances found!` instead of `'10.0.. ' is not an IP address! Removing from interface list.`, is it right?

**Comment by philmath-pea** [comment]
yes I upgraded and set ecs containers to use "host" networking configuration and still get the message "No EC2 instances found!" The joiner finds other EC2 instances using hazelcast in a different group but it won't find any of the containerized instances of hazelcast.

**Comment by leszko** [comment]
That's weird, I actually tested it a few times before and it worked for me... 
If you use the "host" network and set the public IP of Hazelcast to the one from EC2 Instance (using `<interface>10.0.*.*</interface>), then technically it's the same as if you'd run it directly on EC2 Instance. 

The next things you could try is if you can try:
1. If your member is started with `10.0.*.*` IP address. You should see in its logs something like: 
```
Members {size:1, ver:1} [
        Member [10.0.0.2]:5701 - ea00b057-f3db-4bb5-9f7b-948db95ee1e4 this
]
```
2. If your member is accessible from the other EC2 Instance, just execute something like: `$ curl 10.0.0.2:5701/hazelcast/health`.

**Comment by philmath-pea** [comment]
These instances are being deploy as part of an ECS cluster so I cannot specify the IP of the members since it could be deploy to any 2 of a 6 node cluster. The member is accessible (I've tested this) but the members cannot find other members in the cluster once started.

**Comment by leszko** [comment]
As mentioned in the first point in my last comment, did you check if your members are assigned with the host IP address (they should , if you use "host" network)? Do you have the host IP in the member logs?

**Comment by markathomas** [comment]
I have a similar problem with Hazelcast 3.10.5 and HZ AWS 2.3 but in my case i don't even see the AWS discovery strategy attempting to locate nodes.  I am using IAM ECS task roles so I would expect to see a log message similar to the following: `Describe instances will be queried with iam-role assigned to EC2 instance, please make sure given iam-role have ec2:DescribeInstances policy attached.`  yet nothing like this in the log.

**Comment by markathomas** [comment]
Here is my config:
```
String cluster = "demo";
        Config config = new Config(cluster);
        String grpName = "demo-cluster";
        config.getGroupConfig().setName(grpName);
        config.getGroupConfig().setPassword("f00b4r!");

        config.getProperties().setProperty(GroupProperty.LOGGING_TYPE.getName(), "slf4j");
        config.getProperties().setProperty(GroupProperty.ENABLE_JMX.getName(), "true");
        config.getProperties().setProperty(GroupProperty.ENABLE_JMX.getName(), "true");
        config.getProperties().setProperty(GroupProperty.SLOW_OPERATION_DETECTOR_STACK_TRACE_LOGGING_ENABLED.getName(), "true");
        config.getProperties().setProperty(GroupProperty.PHONE_HOME_ENABLED.getName(), "false");
        config.getProperties().setProperty(GroupProperty.EVENT_QUEUE_TIMEOUT_MILLIS.getName(), "5000");
        config.getProperties().setProperty(GroupProperty.OPERATION_CALL_TIMEOUT_MILLIS.getName(), "10000");
        config.getProperties().setProperty(GroupProperty.CONNECT_ALL_WAIT_SECONDS.getName(), "60");
        config.getProperties().setProperty(GroupProperty.HEARTBEAT_INTERVAL_SECONDS.getName(), "1");
        config.getProperties().setProperty(GroupProperty.MAX_NO_HEARTBEAT_SECONDS.getName(), "10");
        config.getProperties().setProperty(GroupProperty.MEMBER_LIST_PUBLISH_INTERVAL_SECONDS.getName(), "30");
        config.getProperties().setProperty(GroupProperty.MERGE_NEXT_RUN_DELAY_SECONDS.getName(), "30");
        config.getProperties().setProperty(GroupProperty.PREFER_IPv4_STACK.getName(), "true");
        config.getProperties().setProperty(GroupProperty.DISCOVERY_SPI_ENABLED.getName(), "true");

        String ip = this.getDockerHostIP();
        Logger logger = LoggerFactory.getLogger(getClass());
        config.getProperties().setProperty("hazelcast.local.localAddress", ip);
        logger.debug("set hazelcast.local.localAddress to {}", ip);
        config.getProperties().setProperty("hazelcast.local.publicAddress", ip + ":" + Optional.ofNullable(System.getenv("HZ_PORT")).orElse("5701"));
        System.setProperty("hazelcast.local.publicAddress", ip + ":" + Optional.ofNullable(System.getenv("HZ_PORT")).orElse("5701"));
        config.getNetworkConfig().setPublicAddress(ip + ":" + Optional.ofNullable(System.getenv("HZ_PORT")).orElse("5701"));
        logger.debug("set network config public address to {}", ip + ":" + Optional.ofNullable(System.getenv("HZ_PORT")).orElse("5701"));

        //config.getNetworkConfig().setPort(this.port);
        JoinConfig joinConfig = config.getNetworkConfig().getJoin();
        joinConfig.getAwsConfig().setEnabled(false);
        joinConfig.getTcpIpConfig().setEnabled(false);
        joinConfig.getMulticastConfig().setEnabled(false);

        AwsDiscoveryStrategyFactory awsDiscoveryStrategyFactory = new AwsDiscoveryStrategyFactory();
        Map<String, Comparable> properties = new HashMap<>();
        //properties.put("access-key","my-access-key");
        //properties.put("secret-key","my-secret-key");
        //properties.put("iam-role","bridge-server-ecs-role");
        properties.put("region","us-east-1");
        properties.put("host-header","ec2.amazonaws.com");
        properties.put("security-group-name","App.BoxView.com");
        properties.put("tag-key","demo-cluster");
        properties.put("tag-value","cluster1");
        properties.put("hz-port","5701-5708");
        DiscoveryStrategyConfig discoveryStrategyConfig = new DiscoveryStrategyConfig(awsDiscoveryStrategyFactory, properties);
        joinConfig.getDiscoveryConfig().addDiscoveryStrategyConfig(discoveryStrategyConfig);

        //if you want to configure multiple discovery strategies at once
        ArrayList<DiscoveryStrategyConfig> discoveryStrategyConfigs = new ArrayList<>();
        joinConfig.getDiscoveryConfig().setDiscoveryStrategyConfigs(discoveryStrategyConfigs);
```

NOTE: classic AWS joiner works just fine.

**Comment by philmath-pea** [comment]
@leszko yes both instances are reporting the host ip address in the logs and report something like this - 

`Members {size:1, ver:1} [
Member [10.25.10.57]:5858 - c6e272ba-4387-447c-a7d8-2a768a9aef5f this]
Oct 04, 2018 1:18:04 PM com.hazelcast.core.LifecycleService
INFO: [10.25.10.57]:5858 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] [10.25.10.57]:5858 is STARTED`

**Comment by leszko** [comment]
@philmath-pea , I think the issue may be that the your member port `5858` is outside of the range of ports you specify in the `hz-port` discovery property. Could you check if that's not the case?

@markathomas , why have you commented out both access-key/secret-key and iam-role? I think you need to set up either access-key+secret-key or iam-role to get it working.

**Comment by markathomas** [comment]
@leszko you don't need either.  Check out `AwsDiscoveryStrategy` code for details.

**Comment by philmath-pea** [comment]
@leszko I  just change the port to 5701 . Now it does not report " No EC2 instances found!" so that is progress. I still don't see a log specifying they found each other either. 

curl 10.25.10.57:5701/hazelcast/health returns 

`closed. Reason: REST or SSL not enabled` and `closed. Reason: Memcached or SSL not enabled`

alternately.

**Comment by leszko** [comment]
@philmath-pea , could you paste here the logs you get now?

@markathomas You're right. I'll check why it doesn't work.

**Comment by philmath-pea** [comment]
Both nodes looks like this, except IP address difference 

`
08:42:20
log4j:WARN Please initialize the log4j system properly.

08:42:20
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

08:42:26
Oct 08, 2018 8:42:26 AM com.hazelcast.instance.AddressPicker

08:42:26
INFO: [LOCAL] [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Interfaces is enabled, trying to pick one address matching to one of: [10.25.10.*]

08:42:26
Oct 08, 2018 8:42:26 AM com.hazelcast.instance.AddressPicker

08:42:26
INFO: [LOCAL] [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Prefer IPv4 stack is true.

08:42:26
Oct 08, 2018 8:42:26 AM com.hazelcast.instance.AddressPicker

08:42:26
INFO: [LOCAL] [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Picked [10.25.10.119]:5701, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=5701], bind any local is true

08:42:26
Oct 08, 2018 8:42:26 AM com.hazelcast.system

08:42:26
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Hazelcast 3.10 (20180424 - d9afa99) starting at [10.25.10.119]:5701

08:42:26
Oct 08, 2018 8:42:26 AM com.hazelcast.system

08:42:26
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Copyright (c) 2008-2018, Hazelcast, Inc. All Rights Reserved.

08:42:26
Oct 08, 2018 8:42:26 AM com.hazelcast.system

08:42:26
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Configured Hazelcast Serialization version: 1

08:42:26
Oct 08, 2018 8:42:26 AM com.hazelcast.instance.Node

08:42:26
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] A non-empty group password is configured for the Hazelcast member. Starting with Hazelcast version 3.8.2, members with the same group name, but with different group passwords (that do not use authentication) form a cluster. The group password configuration will be removed completely in a future release.

08:42:27
Oct 08, 2018 8:42:27 AM com.hazelcast.spi.impl.operationservice.impl.BackpressureRegulator

08:42:27
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Backpressure is disabled

08:42:27
Oct 08, 2018 8:42:27 AM com.hazelcast.spi.impl.operationservice.impl.InboundResponseHandlerSupplier

08:42:27
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Running with 2 response threads

08:42:28
Oct 08, 2018 8:42:28 AM com.hazelcast.instance.Node

08:42:28
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Activating Discovery SPI Joiner

08:42:28
Oct 08, 2018 8:42:28 AM com.hazelcast.spi.impl.operationexecutor.impl.OperationExecutorImpl

08:42:28
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Starting 2 partition threads and 3 generic threads (1 dedicated for priority tasks)

08:42:28
Oct 08, 2018 8:42:28 AM com.hazelcast.internal.diagnostics.Diagnostics

08:42:28
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Diagnostics disabled. To enable add -Dhazelcast.diagnostics.enabled=true to the JVM arguments.

08:42:28
Oct 08, 2018 8:42:28 AM com.hazelcast.core.LifecycleService

08:42:28
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] [10.25.10.119]:5701 is STARTING

08:42:33
Oct 08, 2018 8:42:33 AM com.hazelcast.system

08:42:33
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Cluster version set to 3.10

08:42:33
Oct 08, 2018 8:42:33 AM com.hazelcast.internal.cluster.ClusterService

08:42:33
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10]

08:42:33
Members {size:1, ver:1} [

08:42:33
Member [10.25.10.119]:5701 - 577a22ef-ad38-4d2c-a8a4-397f44b5fa25 this

08:42:33
]

08:42:33
Oct 08, 2018 8:42:33 AM com.hazelcast.core.LifecycleService

08:42:33
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] [10.25.10.119]:5701 is STARTED

08:42:39
Oct 08, 2018 8:42:39 AM com.pea.pns.spring.PNSCacheRegionFactory

08:42:39
INFO: Starting up PNSCacheRegionFactory

08:42:53
Oct 08, 2018 8:42:53 AM com.hazelcast.internal.diagnostics.HealthMonitor

08:42:53
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] processors=2, physical.memory.total=7.8G, physical.memory.free=3.4G, swap.space.total=0, swap.space.free=0, heap.memory.used=336.0M, heap.memory.free=466.0M, heap.memory.total=802.0M, heap.memory.max=1.8G, heap.memory.used/total=41.89%, heap.memory.used/max=18.46%, minor.gc.count=20, minor.gc.time=891ms, major.gc.count=4, major.

08:42:57
Oct 08, 2018 8:42:57 AM org.apache.catalina.startup.HostConfig deployWAR

08:42:57
INFO: Deployment of web application archive /usr/local/tomcat/webapps/v3.war has finished in 47,821 ms

08:42:57
Oct 08, 2018 8:42:57 AM org.apache.catalina.startup.HostConfig deployDirectory

08:42:57
INFO: Deploying web application directory /usr/local/tomcat/webapps/examples

08:42:58
Oct 08, 2018 8:42:58 AM com.hazelcast.internal.partition.impl.PartitionStateManager

08:42:58
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Initializing cluster partition table arrangement...

08:42:58
Oct 08, 2018 8:42:58 AM org.apache.catalina.startup.HostConfig deployDirectory

08:42:58
INFO: Deployment of web application directory /usr/local/tomcat/webapps/examples has finished in 634 ms

08:42:58
Oct 08, 2018 8:42:58 AM org.apache.catalina.startup.HostConfig deployDirectory

08:42:58
INFO: Deploying web application directory /usr/local/tomcat/webapps/docs

08:42:58
Oct 08, 2018 8:42:58 AM org.apache.catalina.startup.HostConfig deployDirectory

08:42:58
INFO: Deployment of web application directory /usr/local/tomcat/webapps/docs has finished in 63 ms

08:42:58
Oct 08, 2018 8:42:58 AM org.apache.catalina.startup.HostConfig deployDirectory

08:42:58
INFO: Deploying web application directory /usr/local/tomcat/webapps/manager

08:42:58
Oct 08, 2018 8:42:58 AM org.apache.catalina.startup.HostConfig deployDirectory

08:42:58
INFO: Deployment of web application directory /usr/local/tomcat/webapps/manager has finished in 325 ms

08:42:58
Oct 08, 2018 8:42:58 AM org.apache.catalina.startup.HostConfig deployDirectory

08:42:58
INFO: Deploying web application directory /usr/local/tomcat/webapps/host-manager

08:42:58
Oct 08, 2018 8:42:58 AM org.apache.catalina.startup.HostConfig deployDirectory

08:42:58
INFO: Deployment of web application directory /usr/local/tomcat/webapps/host-manager has finished in 65 ms

08:42:58
Oct 08, 2018 8:42:58 AM org.apache.catalina.startup.HostConfig deployDirectory

08:42:58
INFO: Deploying web application directory /usr/local/tomcat/webapps/ROOT

08:42:58
Oct 08, 2018 8:42:58 AM org.apache.catalina.startup.HostConfig deployDirectory

08:42:58
INFO: Deployment of web application directory /usr/local/tomcat/webapps/ROOT has finished in 34 ms

08:42:58
Oct 08, 2018 8:42:58 AM org.apache.coyote.AbstractProtocol start

08:42:58
INFO: Starting ProtocolHandler ["http-apr-8080"]

08:42:58
Oct 08, 2018 8:42:58 AM org.apache.coyote.AbstractProtocol start

08:42:58
INFO: Starting ProtocolHandler ["ajp-apr-8009"]

08:42:58
Oct 08, 2018 8:42:58 AM org.apache.catalina.startup.Catalina start

08:42:58
INFO: Server startup in 49104 ms

11:00:19
Oct 08, 2018 11:00:19 AM com.hazelcast.map.impl.eviction.EvictionChecker

11:00:19
WARNING: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] The max size configuration for map "Organizations" does not allow any data in the map. Given the current cluster size of 1 members with 271 partitions, max size should be at least 271. Map size is forced set to 271 for backward compatibility

11:45:21
Oct 08, 2018 11:45:21 AM com.hazelcast.nio.tcp.TcpIpAcceptor

11:45:21
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Accepting socket connection from /127.0.0.1:38910

11:45:21
Oct 08, 2018 11:45:21 AM com.hazelcast.nio.tcp.TcpIpConnectionManager

11:45:21
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Established socket connection between /127.0.0.1:5701 and /127.0.0.1:38910

11:45:23
Oct 08, 2018 11:45:23 AM com.hazelcast.nio.tcp.TcpIpConnection

11:45:23
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Connection[id=1, /127.0.0.1:5701->/127.0.0.1:38910, endpoint=null, alive=false, type=NONE] closed. Reason: Memcached or SSL not enabled

11:45:30
Oct 08, 2018 11:45:30 AM com.hazelcast.nio.tcp.TcpIpAcceptor

11:45:30
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Accepting socket connection from /10.25.0.197:65514

11:45:30
Oct 08, 2018 11:45:30 AM com.hazelcast.nio.tcp.TcpIpConnectionManager

11:45:30
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Established socket connection between /10.25.10.119:5701 and /10.25.0.197:65514

11:45:32
Oct 08, 2018 11:45:32 AM com.hazelcast.nio.tcp.TcpIpConnection

11:45:32
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Connection[id=2, /10.25.10.119:5701->/10.25.0.197:65514, endpoint=null, alive=false, type=NONE] closed. Reason: Memcached or SSL not enabled

11:46:44
Oct 08, 2018 11:46:44 AM com.hazelcast.nio.tcp.TcpIpAcceptor

11:46:44
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Accepting socket connection from /127.0.0.1:38934

11:46:44
Oct 08, 2018 11:46:44 AM com.hazelcast.nio.tcp.TcpIpConnectionManager

11:46:44
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Established socket connection between /127.0.0.1:5701 and /127.0.0.1:38934

11:46:44
Oct 08, 2018 11:46:44 AM com.hazelcast.nio.tcp.TcpIpConnection

11:46:44
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Connection[id=3, /127.0.0.1:5701->/127.0.0.1:38934, endpoint=null, alive=false, type=NONE] closed. Reason: REST or SSL not enabled

14:39:35
Oct 08, 2018 2:39:35 PM com.hazelcast.instance.Node

14:39:35
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Running shutdown hook... Current state: ACTIVE

14:39:35
Oct 08, 2018 2:39:35 PM org.apache.coyote.AbstractProtocol pause

14:39:35
INFO: Pausing ProtocolHandler ["http-apr-8080"]

14:39:35
Oct 08, 2018 2:39:35 PM org.apache.coyote.AbstractProtocol pause

14:39:35
INFO: Pausing ProtocolHandler ["ajp-apr-8009"]

14:39:35
Oct 08, 2018 2:39:35 PM org.apache.catalina.core.StandardService stopInternal

14:39:35
INFO: Stopping service Catalina

14:39:35
Oct 08, 2018 2:39:35 PM com.hazelcast.core.LifecycleService

14:39:35
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] [10.25.10.119]:5701 is SHUTTING_DOWN

14:39:35
Oct 08, 2018 2:39:35 PM com.hazelcast.instance.Node

14:39:35
WARNING: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Terminating forcefully...

14:39:35
Oct 08, 2018 2:39:35 PM com.hazelcast.instance.Node

14:39:35
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Shutting down connection manager...

14:39:35
Oct 08, 2018 2:39:35 PM com.hazelcast.instance.Node

14:39:35
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Shutting down node engine...

14:39:35
Oct 08, 2018 2:39:35 PM com.hazelcast.instance.NodeExtension

14:39:35
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Destroying node NodeExtension.

14:39:35
Oct 08, 2018 2:39:35 PM com.hazelcast.instance.Node

14:39:35
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] Hazelcast Shutdown is completed in 54 ms.

14:39:35
Oct 08, 2018 2:39:35 PM com.hazelcast.core.LifecycleService

14:39:35
INFO: [10.25.10.119]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.10] [10.25.10.119]:5701 is SHUTDOWN

14:39:35
Oct 08, 2018 2:39:35 PM org.apache.coyote.AbstractProtocol stop

14:39:35
INFO: Stopping ProtocolHandler ["http-apr-8080"]

14:39:36
Oct 08, 2018 2:39:36 PM org.apache.coyote.AbstractProtocol stop

14:39:36
INFO: Stopping ProtocolHandler ["ajp-apr-8009"]

14:39:36
Oct 08, 2018 2:39:36 PM org.apache.coyote.AbstractProtocol destroy

14:39:36
INFO: Destroying ProtocolHandler ["http-apr-8080"]

14:39:36
Oct 08, 2018 2:39:36 PM org.apache.coyote.AbstractProtocol destroy

14:39:36
`

**Comment by leszko** [comment]
Hi @philmath-pea @markathomas , I double checked Hazelcast on AWS ECS and it seems to work correctly. I even created a code sample here: https://github.com/leszko/hazelcast-code-samples/tree/aws-ecs/hazelcast-integration/aws-ecs. Please have a look and check if it works for you. I'll publish it as a Blog Post as well.

As of your configurations, I'm not sure why they don't work. It may be a matter of wrong tags or not setting the network to "host". Or many other things. Check the code sample and if it works, then try to adapt your code to work in a similar manner. Hope it helps.

**Comment by philmath-pea** [comment]
thank you @leszko I will check it out and let you know how it goes.

**Comment by leszko** [comment]
@markathomas , yes, but the value of `hazelcast.local.publicAddress` will differ depending on the EC2 Instance it's running on. Do you have any method to set it dynamically?

**Comment by markathomas** [comment]
@leszko I query the EC2 metadata at `http://169.254.169.254/latest/meta-data/local-ipv4` for the Docker host IP and use that + port for `hazelcast.local.publicAddress`.  That IP won't change as long as the host is running.

**Comment by markathomas** [comment]
For public address for WAN config you can query `http://169.254.169.254/latest/meta-data/public-ipv4`

**Comment by philmath-pea** [comment]
@leszko looks like I'm getting closer.. with your exact config I'm seeing this error. I think it's probably b/c the node is reporting the internal docker ip instead of the host IP all though host networking is still enabled on the ECS task.

```INFO: [172.17.0.1]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.7-EA] Established socket connection between /10.25.10.228:37545 and /10.25.10.119:5701
Oct 16, 2018 1:19:11 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [172.17.0.1]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.7-EA] Closing connection due to exception in NonBlockingSocketReader
Oct 16, 2018 1:19:11 PM com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketReader
INFO: [172.17.0.1]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.7-EA] hz._hzInstance_1_3.5.20-SNAPSHOT-hazelcast-v3-admin.IO.thread-in-0 Closing socket to endpoint [10.25.10.119]:5701, Cause:java.io.EOFException: Remote socket closed!
Oct 16, 2018 1:21:11 PM com.hazelcast.nio.tcp.SocketAcceptorThread
INFO: [172.17.0.1]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.7-EA] Accepting socket connection from /10.25.10.119:59207
Oct 16, 2018 1:21:11 PM com.hazelcast.nio.tcp.TcpIpConnectionManager
INFO: [172.17.0.1]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.7-EA] Established socket connection between /10.25.10.228:5701 and /10.25.10.119:59207
Oct 16, 2018 1:21:11 PM com.hazelcast.nio.tcp.TcpIpConnectionManager
WARNING: [172.17.0.1]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.7-EA] Wrong bind request from [172.17.0.1]:5701! This node is not requested endpoint: [10.25.10.228]:5701
Oct 16, 2018 1:21:11 PM com.hazelcast.nio.tcp.TcpIpConnection
INFO: [172.17.0.1]:5701 [3.5.20-SNAPSHOT-hazelcast-v3-admin] [3.7-EA] Wrong bind request from [172.17.0.1]:5701! This node is not requested endpoint: [10.25.10.228]:5701```

**Comment by leszko** [comment]
@philmath-pea Have you set the network as "host"?

**Comment by philmath-pea** [comment]
Yep, my old config was reporting the host IP

```
 TaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
            Family: api-service
            ExecutionRoleArn: !Ref TaskRole
            NetworkMode: "host"
            ContainerDefinitions:
```

**Comment by philmath-pea** [comment]
not sure what I did but.. wooohoo seems like it's working. thanks for all your help. @leszko 

```Members [2] {
19:53:39
Member [10.25.10.201]:5701 - 567ca12b-7714-404c-b904-b46a4a7f73e8 this
19:53:39
Member [10.25.10.203]:5701 - 0f94d168-96cf-4d15-9930-1b4601aed509
19:53:39
}```

**Comment by markathomas** [comment]
@philmath-pea could you share your config so others can benefit in the future?

**Comment by philmath-pea** [comment]
the configuration @leszko posted here is what worked for me: https://github.com/leszko/hazelcast-code-samples/tree/aws-ecs/hazelcast-integration/aws-ecs

the main issue I had with making that work is I had left (from a previous config attempt) the AWS key/secret in the config 
```
.setAccessKey(properties.getAccessKey())
 .setSecretKey(properties.getSecretKey())
```
not sure why but until I removed that Hazelcast reported the internal docker IP, not the host IP and could not create the cluster.

**Comment by leszko** [comment]
Great. I'm super happy it worked for you @philmath-pea .

I'll also try to make a Blog Post on that, so that it's simpler to set up in the future. Closing the issue. Please feel free to reopen if needed.
