### ISSUE TITLE
Release version 3.7

### ISSUE THREAD

**Issue by Stephan202** [hazelcast/hazelcast-aws#8]
After some digging around it is my understanding that:

1. This module is to replace `hazelcast-cloud`.
2. This module has not yet been released under its new name `hazelcast-aws`.
3. The unreleased version of the code matches (nearly?) completely `hazelcast-cloud:3.6.5`.

I'd like to ask you to release `hazelcast-aws:3.7` anyway. This way it's much clearer for users how to upgrade from Hazelcast 3.6.5 to 3.7, because then:

1. The replacement can actually be found in Maven Central.
2. One can keep version numbers in sync.

**Comment by Stephan202** [comment]
NB: The `artifactId` should then also be updated in the [documentation](https://hazelcast.org/plugins/?type=cloud-discovery#aws).

**Comment by mesutcelik** [comment]
Thanks for the heads up! @Stephan202 

We will be releasing hazelcast-aws soon but versioning won't be in sync. After moving modules to their own repositories, they will have their own versions. As this is completely new name and not available in maven central, we will release it as v1.0 and planning to implement Discovery SPI based one in future. That will probably be v.2.0

Versioning related info will be available on README.md file.

**Comment by Stephan202** [comment]
I see `v1.0` was released just now. Thanks!
