### ISSUE TITLE
Need an update on the EC2 instance types for the AWS guide.

### ISSUE THREAD

**Issue by Serdaro** [hazelcast/hazelcast-aws#81]
There are some missing types which are asked by the prospects. Once they are provided through this issue, the AWS guide (https://hazelcast.com/resources/amazon-ec2-deployment-guide/) will be updated accordingly.

**Comment by Serdaro** [comment]
I think @tom-hazelcast  has been on it.

**Comment by leszko** [comment]
@tom-hazelcast are you still working on this issue?

**Comment by neilstevenson** [comment]
The guide (`Hazelcast_IMDG_Amazon_EC2_Deployment_Guide_SPOT_Letter_v2.3.pdf`) still mentions R3

R3 is no longer available

AWS have moved on to R4 and now R5 - https://aws.amazon.com/ec2/instance-types/#Memory_Optimized

**Comment by mesutcelik** [comment]
@neilstevenson Did you check with @7erry ? He is the one who is maintaining that document.

**Comment by neilstevenson** [comment]
It should be the issue owner who chases along shouldn't it ?  I only raised it

**Comment by leszko** [comment]
@mesutcelik have you sorted it out? Can we close this issue?

**Comment by mesutcelik** [comment]
I think we can close it. I am sure @tom-hazelcast has already worked on it but as I mentioned, we are not tracking DevOps guide issues here.
