### ISSUE TITLE
Missing docs on required IAM role privileges

### ISSUE THREAD

**Issue by gsaslis** [hazelcast/hazelcast-aws#9]
I am struggling to find what the required roles / policies are for the AWS IAM user that I have just created for Hazelcast. 

(Disclaimer: I already know a gung-ho approach like 'ec2 admin' or sth would work, but I am looking for the specific list of the permissions required.)

Can somebody please point me to a relevant doc? (In return, I'll happily open a PR so that it's also documented in this repo too!)

**Comment by gsaslis** [comment]
FWIW - by trial and error - I have come to the conclusion one would need the following `ec2:Describe*`

I also ran across this [SO answer](http://stackoverflow.com/a/30687877/983387), according to which one would just need the `ec2:DescribeInstances` action in their policy. Just haven't confirmed this yet.

**Comment by bilalyasar** [comment]
yes, user should give at least describe instances policy.
closed by https://github.com/hazelcast/hazelcast-aws/commit/9c5b2f3f42b7767b4fa6d04aeb262bea7bff5470

**Comment by gsaslis** [comment]
awesome - thanks for confirming that @bilalyasar !
